# Generated by Django 3.1 on 2021-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210811_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='12', upload_to='users/images'),
            preserve_default=False,
        ),
    ]
