# Generated by Django 3.1 on 2021-08-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='users.customuser'),
            preserve_default=False,
        ),
    ]
