# Generated by Django 3.1 on 2021-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210817_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritearticle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
