# Generated by Django 3.1 on 2021-08-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favoritearticle_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='main.article')),
            ],
        ),
    ]
